"""Wiki writer. Red-team rules applied:

- Frontmatter is generated by code (yaml.safe_dump), never by the LLM.
- The Sources section is appended by code from actually-fetched URLs;
  bare URLs the LLM invented are stripped from the body.
- index.md is rebuilt deterministically from the directory listing.
- Logs are one file per night (log/YYYY-MM-DD.md) — sync-engine friendly.
- Raw source snapshots go to raw/ so every claim stays auditable.
"""

import re
import zlib
from pathlib import Path

import yaml

from .util import atomic_write, now_iso, slugify, today_str

URL_RE = re.compile(r'https?://\S+')

# Files maintained by code at the vault root that are not wiki pages
NON_PAGE_FILES = ('index.md', 'nightly-report.md')


def frontmatter(fields: dict) -> str:
    return f'---\n{yaml.safe_dump(fields, sort_keys=False).strip()}\n---'


def write_page(vault: Path, title: str, body: str, sources: list,
               run_id: str, question_id: int, tags: list[str]) -> Path:
    allowed = {s.url for s in sources}
    body = URL_RE.sub(lambda m: m.group(0) if m.group(0).rstrip('.,)')
                      in allowed else '[link removed — not in sources]', body)
    fm = frontmatter({
        'title': title,
        'date': now_iso(),
        'run_id': run_id,
        'question_id': question_id,
        'tags': tags,
    })
    source_lines = '\n'.join(
        f'- [S{n}] [{s.title}]({s.url}) ({s.source_type}, accessed {today_str()})'
        for n, s in enumerate(sources, start=1))
    content = (f'{fm}\n\n# {title}\n\n{body.strip()}\n\n'
               f'## Sources\n\n{source_lines}\n')
    # qN- prefix keeps two questions with colliding 64-char slugs distinct
    path = vault / f'q{question_id}-{slugify(title)}.md'
    atomic_write(path, content)
    return path


def save_raw(vault: Path, source, run_id: str) -> None:
    raw_dir = vault / 'raw'
    # crc-of-URL suffix: stable per source, distinct for colliding titles
    name = (f'{slugify(source.title)[:48] or "source"}'
            f'-{zlib.crc32(source.url.encode()) % 100000}')
    fm = frontmatter({'url': source.url, 'fetched': now_iso(),
                      'run_id': run_id})
    atomic_write(raw_dir / f'{name}.md', f'{fm}\n\n{source.content}\n')


def rebuild_index(vault: Path, mission_name: str) -> None:
    lines = [f'# Index — {mission_name}', '',
             f'Rebuilt {now_iso()} by researchd. Do not edit by hand.', '']
    for page in sorted(vault.glob('*.md')):
        if page.name in NON_PAGE_FILES:
            continue
        title, date = page.stem, ''
        try:
            text = page.read_text(encoding='utf-8')
            if text.startswith('---'):
                fm = yaml.safe_load(text.split('---', 2)[1])
                if isinstance(fm, dict):
                    title = fm.get('title', title)
                    date = str(fm.get('date', ''))[:10]
        except (yaml.YAMLError, IndexError):
            pass  # unparseable frontmatter: list it anyway, never crash
        lines.append(f'- [[{page.stem}]] — {title}' + (f' ({date})' if date else ''))
    atomic_write(vault / 'index.md', '\n'.join(lines) + '\n')


def append_log(vault: Path, entry: str) -> None:
    log_path = vault / 'log' / f'{today_str()}.md'
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with open(log_path, 'a', encoding='utf-8') as f:
        f.write(f'## [{now_iso()}] {entry}\n')


def write_report(vault: Path, run_id: str, status: str,
                 summary_lines: list[str]) -> Path:
    body = '\n'.join(f'- {line}' for line in summary_lines)
    path = vault / 'nightly-report.md'
    atomic_write(path, (f'# Nightly Report — {today_str()}\n\n'
                        f'run_id: `{run_id}` — status: **{status}**\n\n{body}\n'))
    return path
